ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Old version of image-proc has bug that prevents remapping its topics.
RUN apt-get update && apt-get install -y \
  ros-${ROS_DISTRO}-image-proc \
  ros-${ROS_DISTRO}-ros-gz \
  ros-${ROS_DISTRO}-librealsense2* \
  ros-${ROS_DISTRO}-realsense2-* \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get clean
